
# Context

The last assessment for Pacific Cod (*Gadus macrocephalus*) in British Columbia (BC) was completed in 2020 [@dfo2021].
The 2020 stock assessment for Pacific Cod (*Gadus macrocephalus*), which is not prescribed as a major stock, found the Area 3CD (West Coast of Vancouver Island: WCVI) stock to be in the Cautious Zone with > 99% probability [@dfo2021].
This followed a notable reduction in the 2018 WCVI survey index (approximately 26--27% of the 2014 and 2016 observations (Figure \@ref(fig:surv-canadian); Table \@ref(tab:surv-canadian-table)).
Given the low index point in 2018, the 2020 Science Response recommended updating the assessment when new survey information became available [@dfo2021].

Due to the COVID-19 pandemic, the scheduled 2020 WCVI Synoptic Bottom Trawl Survey was postponed to 2021, then returned to its regular biennial schedule in 2022.
Both the 2021 and 2022 index points were of a similar low magnitude to the 2018 observation (Figure \@ref(fig:surv-canadian)).
Catches from 2018--2020 were also lower than in previous years (Table \@ref(tab:tab-catch-3cd), Figure \@ref(fig:fig-catch-3cd)).
The commercial CPUE index decreased substantially in 2018 but has increased slightly since then, with increases in commercial catch (Figure \@ref(fig:fig-modern-cpue-3cd), Table \@ref(tab:tab-catch-3cd)).

The stock assessment is a Bayesian delay-difference model [@deriso1980], fit to commercial and survey indices of abundance, commercial catch, and an index of commercial annual mean weight [@forrest2020]. The commercial mean weight index is derived from commercial length samples [see Appendix C of @forrest2020 for methodology], and provides information about scale and recruitment strength to the model.
Due to COVID-19 and a subsequent shift towards at-sea electronic monitoring, there has been no at-sea biological sampling on commercial trawl vessels since 2019.
However, even before the pandemic, there has been a notable reduction in biological sampling of Pacific cod on commercial vessels since 2016 (Appendix A).

A Request for Science Information and Advice (RSIA) for Pacific Cod was issued in 2022 for both the 3CD and 5ABCD (Hecate Strait and Queen Charlotte Sound) stocks.
The request had two steps: 1) an evaluation to assess the potential sensitivity of the stock assessment to missing length data from the commercial fishery; and 2) update the status of both stocks.
The request advised to only proceed to Step 2 if the missing length data were "deemed to not be of significance to the quality and rigour of the scientific advice".
Using the 2020 assessment model, the authors presented several sensitivity analyses to the Pacific Cod Technical Working Group (TWG) to show the potential effects of the loss of commercial length samples on predicted stock status.
The TWG evaluated a generalized linear model (GLM) for predicting the commercial mean weight index from a survey annual mean weight index derived from WCVI survey samples.
The TWG found that the GLM provided acceptable predictions of the commercial annual mean weight index for the Area 3CD stock.
The GLM did not have acceptable predictive power for the 5ABCD stock.
Because of this and limited staff resources, the TWG did not proceed with Step 2 of the RSIA in 2022.
The Pacific Groundfish Management Unit did not request updated catch advice for 2023.
However, given the three low index points in 2018, 2021 and 2022, Science issued a RSIA requesting a stock status update to ensure all three of these index points are considered in a timely evaluation of stock status.

The Fish Stocks provisions (FSP) of Canada's [Fisheries Act](https://laws-lois.justice.gc.ca/eng/acts/f-14/page-2.html#h-1175547) require that a rebuilding plan be developed for major fish stocks that have declined to or below their limit reference point (LRP).
While the FSP only apply to major stocks prescribed in the *Fishery (General) Regulations*, [guidance](https://www.dfo-mpo.gc.ca/reports-rapports/regs/sff-cpd/precautionary-precaution-eng.htm#toc_2.1) has been provided, which states that, for stocks not subject to the FSP, DFO's Precautionary Approach (PA) Policy [@dfo2009] still applies:

*"[...] under the [PA] policy, the requirement to develop a rebuilding plan is triggered once the stock declines to, or below, its LRP. However, in keeping with the 2009 PA Policy, if a fish stock is decreasing and approaching the LRP, management measures must encourage stock growth and arrest preventable declines, and the development of a rebuilding plan should be initiated sufficiently in advance to ensure that the plan is ready to be implemented if a stock declines to its LRP."*

For the purpose of triggering a rebuilding plan, the guidance provides the following definitions of whether a stock is at or below its LRP:

*"[A stock] is considered to be at or below its LRP if the terminal year stock status indicator is estimated to be at or below the LRP with a greater than 50% probability or if the projected stock status indicator falls below the LRP with a greater than 50% probability under a zero catch scenario in a 1-year projection, unless an alternative method or probability is defined in a stock-specific precautionary approach framework."*

This Science Response reports results from the Science Response Process of December 2022 on the Stock Status Update of British Columbia Pacific Cod (*Gadus macrocephalus*) in Area 3CD in 2023.
This stock status update uses the same model configurations as the 2018 and 2020 assessments [@forrest2020; @dfo2021], including model-averaged stock status based on the same seven sensitivity scenarios as in 2018 and 2020.
Due to the ongoing absence of commercial length samples, this update uses the GLM developed in 2022, which predicts commercial mean weight index values from a survey mean weight index, to update the last five years of the annual commercial mean weight index.
The survey mean weight index and the GLM are described in Appendices B and C.

# Background

Pacific Cod (or Grey Cod) is a relatively short-lived (~10--13 *y*), fast-growing member of the family Gadidae.
It is distributed throughout the North Pacific Ocean, and throughout the waters of BC, typically in depth ranges up to 200 m. 
Four stocks of Pacific Cod are defined for management purposes on the BC coast: Strait of Georgia (4B), West Coast Vancouver Island (3CD), Queen Charlotte Sound (5AB), and Hecate Strait (5CD).
This assessment provides science advice for the stock of the West Coast Vancouver Island (3CD) (Figure \@ref(fig:fig-map)). 

## Description of the fishery

Pacific Cod in BC are caught almost entirely in the groundfish bottom trawl fishery, which is part of BC's integrated groundfish fishery [@dfo2017].
They are caught in small quantities in the groundfish longline fishery (around 0.5% of the total annual catch on average), which is also part of the integrated groundfish fishery.
The depth range of capture in 5ABCD ranges from around 60--200 m, with data showing a shift to deeper depths since 1996 [@forrest2020].
Currently, the majority of the BC Pacific Cod catch is taken in Area 5CD.
Commercial catches also come from Area 5AB and Area 3CD. 
Near negligible catch is taken from the west coast of Haida Gwaii, Area 5E (< 0.5% of total average annual catch since 1985).
The BC integrated fishery is subject to 100% at-sea and dockside monitoring.
Between 1996 and 2020, all bottom trawl vessels carried observers who record the catch of each species and estimate quantities of released (discarded) fish.
Since the COVID-19 pandemic, the fishery has shifted towards electronic monitoring on trawl vessels, which has impacted the availability of commercial biological samples (see Context).

# Analysis and Response

## Data

Data were extracted from DFO databases using methods described in @forrest2020.
Biological data from fishery-independent and commercial fishery sources were available up until 2019.
Catch data were updated to 2020, with data extrapolated from October 1, 2020 to the end of the fishing year (see below).
For each area, models were fit to the following data: commercial catch, fishery-independent indices of abundance, commercial catch per unit effort (CPUE), and annual mean weight of fish in the commercial catch.

### Commercial catch

Commercial catch data (Table \@ref(tab:tab-catch-3cd) and Figure \@ref(fig:fig-catch-3cd) were extracted from three different databases held by DFO: *GFCatch* (Canadian trawl landings, 1954--1995); *PacHarvTrawl* (Canadian trawl landings, 1996 to March 31, 2007); and *GFFOS* (Canadian trawl landings, April 1, 2007 to March 31, 2022).
Catch data prior to 1981 include catch by US vessels [@forrest2015; @forrest2020].
Fishing years are defined as beginning on April 1 for all years, and are referenced by starting year, e.g., fishing year 1957 runs from April 1, 1957 to March 31, 1958 [see @forrest2020].

Prior to the introduction of at-sea observer coverage in 1996, estimates of discards for the period 1956--1995 were obtained from fishing logbooks in the absence of at-sea observers.
Pre-1996 discards are, therefore, a major source of uncertainty in this assessment.
Estimates in years following the introduction of 100% at-sea observer coverage in 1996 are considered to be  accurate.
Pacific Cod can be legally discarded by trawlers in BC.
However, between 1996 and 2019, on-board observers first estimated the quantity being discarded, which was counted against the vessel's quota.
Discard estimates are still counted against the vessel's quota, but the estimates are now made via the electronic monitoring system and fisher logbooks.
In addition to providing greater accuracy in reporting of discards since 1996, counting discards against the vessel's quota provides greater incentives to avoid discarding.

### Canadian bottom trawl surveys

Survey indices (Table \@ref(tab:surv-canadian-table) and Figure \@ref(fig:surv-canadian)) were calculated using a swept area analysis, documented in Appendix A of @forrest2020.
Abundance in Area 3CD (Figure \@ref(fig:fig-map)) is indexed by the WCVI Synoptic Survey.
The survey was first conducted in 2004 and is conducted in alternating (even-numbered) years.
Due to the COVID-19 pandemic the 2020 survey was postponed to 2021, before resuming its even-numbered years schedule in 2022.

For comparison, survey indices in Areas 5AB and 5CD are also shown in (Table \@ref(tab:surv-canadian-table) and Figure \@ref(fig:surv-canadian)).

### NMFS Triennial Survey (in Canadian waters)

An additional relative abundance index for Area 3CD was developed using data from the
National Marine Fisheries Service (NMFS) Triennial survey, which operated off the lower half of WCVI between 1980 and 2001 (Figure \@ref(fig:tri-fig9)).
See Appendix A of @forrest2020 for details.

### Commercial CPUE

Standardized commercial CPUE indices were developed for the historical (1956--1995) and modern (1996--2019) periods (Figures  \@ref(fig:cpue-index-ts-hist) and \@ref(fig:cpue-index-ts-modern)).
The indices were developed using a Tweedie generalized linear mixed model (GLMM) described in detail in Appendix B of @forrest2020.
The historical-period GLMMs included predictors for depth, locality, month, and a locality-year interaction (Figure \@ref(fig:cpue-index-ts-hist)).
The modern-period GLMMs included predictors for depth, latitude, locality, month, vessel, and a locality-year interaction (Figure \@ref(fig:cpue-index-ts-modern)).

### Annual mean weight in commercial catch

The commercial annual mean weight index between 1956 and 2016 was calculated using commercial length samples, with the methodology described in Appendix C of @forrest2020.
Commercial biological samples were available for calculating mean weight from 1956 to 2019 (excluding 2018).

There has been no biological sampling on commercial trawl vessels since 2019.
However, even before the COVID-19 pandemic, there had been a decline in commercial sampling of Pacific Cod, starting in 2016 (Appendix A).
In Area 3CD, only four samples were taken in 2017 (total 300 fish), no samples were taken in 2018, and only two samples were taken in 2019 (total 360 fish).
The samples in 2017 and 2019 were taken from a limited area (Figure \@ref(fig:fig-sample-locations)), especially the 2019 samples, which were also collected on the same vessel.
The 2017 mean weight value was anomalously high (3.024 kg) and, given that it was only based on four samples, it was not used in the 2020 stock assessment update [@dfo2021].
Due to lack of data, the 2020 assessment used the 2019 mean weight value for both 2019 and 2020, although this was not ideal, as the 2019 index point was also based on only two samples.

In the absence of representative biological samples for the last years of the time series, a methodology was developed for predicting the commercial mean weight index from a mean weight index derived from WCVI Synoptic Survey length samples (Appendices B and C).
The methodology was presented to the TWG in 2022 and again in 2023, who found it provided a reasonable fit to the commercial mean weight index derived from commercial data for Area 3CD (see also Appendix C).

The GLM predicted values for the commercial mean weight index only for years when there was a survey (i.e., predicted index values were generated for even-numbered years from 2004 to 2018, then 2021 and 2022; Figure \@ref(fig:all-mean-weight-series-3cd)).
A decision therefore had to be made about how to include the GLM-derived index values in the commercial mean weight index, since there were no GLM-derived values for 2017, 2019 or 2020.

For consistency with previous assessments [@forrest2020; @dfo2021], the model uses the commercial annual mean weight index derived directly from commercial length samples for the years 1956--2016.
Since neither of the previous assessments have used the 2017 index point, it was also omitted from this assessment update.
For 2018--2022, the model uses the 2018, 2021 and 2022 annual mean weight index values derived from the GLM (Figure \@ref(fig:all-mean-weight-series-3cd)).
Values for 2019 and 2020 were interpolated between 2018 and 2021.

The TWG explored a number of sensitivity analyses, which tested model sensitivity to alternative approaches to updating the commercial annual mean weight index, including indices that excluded the interpolated values, did not include the GLM values, or variously included or excluded the 2017 and 2019 index points from the commercial data.
The model was largely insensitive to these alternative treatments, mainly because the GLM-derived index values were consistent with the other data sources in the model (see Reference model results section), resulting in poor fits to alternative versions of the index and, therefore, little impact on recruitment and biomass estimates.

## Stock assessment model

The current stock assessment model is a Bayesian delay-difference model [@deriso1980], fit to survey indices, commercial CPUE, commercial catch data and commercial annual mean weights [@forrest2015; @forrest2020].
The model is fully described in Appendix D of @forrest2020.
All fixed parameters and prior probability distributions for model parameters in the current assessment were the same as those reported in @forrest2020 (see also Table \@ref(tab:tab-param-table-3cd), this document).

@forrest2015 (for Pacific Cod stocks in Areas 5A and 5B) and @forrest2020 used a model-averaging approach to estimate stock status and construct decision tables based on combined posterior samples from several sensitivity cases.
This was to address some of the key irresolvable uncertainties associated with the stock assessment.
Major axes of uncertainty were catchability ($q$) in the indices of abundance, the magnitude of natural mortality ($M$), age at recruitment to the fishery, and the magnitude of observation errors in the surveys and mean weight [@forrest2020].
Details are provided in the model scenarios section.
Other stock assessments that have used a model-averaging approach are Pacific Hake [@stewart2011], Pacific Halibut [@stewart2016], BC Shortspine Thornyhead [@starr2017], BC Walleye Pollock [@starr2018] and several assessments of BC *Sebastes* stocks [e.g., @dfo2019b; @dfo2020a; @dfo2020b].

## Reference points

The DFO Fishery Decision-making Framework Incorporating the Precautionary Approach (PA) Policy [@dfo2009] requires stock status to be characterized using three reference points:

1. An Upper Stock Reference point, USR;
2. A Limit Reference Point, LRP;
3. A Limit Removal Rate, LRR.

The USR and LRP define the threshold of three biomass-based stock status zones defined under the PA Policy [@dfo2009]: Critical Zone (below the LRP); Cautious Zone (above the LRP and below the USR); and Healthy Zone (above the USR).

As in the 2018 assessment [@dfo2019], historical reference points were used to assess stock status, where

1. The USR is the historical mean of the biomass estimates from 1956--2004.

2. The LRP is the lowest estimated biomass agreed upon as an undesirable state to be avoided. For Area 5ABCD this is the estimated biomass in 2000. For Area 3CD it is the estimated biomass in 1986.

3. The LRR is the average fishing mortality rate from 1956--2004.

See @forrest2020 for the history of the choice to use historical reference points for Pacific Cod.
See also @forrest2018 for simulation-testing of historical reference points for the 5CD stock of Pacific Cod.

## Model scenarios

A reference model was established to represent what were considered the most plausible model choices across a range of assumptions.
Key characteristics of the model are provided in Table \@ref(tab:tab-param-table-3cd).
For further details, see @forrest2020.
This model served as the basis from which sensitivity scenarios were developed, altering alternative model assumptions one at a time.
A set of model scenarios was agreed upon at the Canadian Science Advisory Secretariat (CSAS) Regional Peer Review (RPR) meeting for model averaging in the 2018 assessment [@dfo2019].
The same sets were used again in the 2020 stock assessment update [@dfo2021] and here (updated with catch and index data to 2022, with updates to the annual mean weight index described above).
Full details on the model configurations and assumptions for each scenario are provided in @forrest2020.

### Scenarios for model-averaging

The scenarios (Sc) included in the model-averaging set were:

1.	Sc 1a Reference model;
2.	Sc 2d Set the mean of the prior probability distribution for synoptic survey $\ln(q)$ = $\ln(1.0)$;
3.	Sc 2e Increase the standard deviation (SD) for synoptic survey $\ln(q)$ to 0.6;
4.	Sc 3a Set the parameters of the prior probability distribution for $\ln(M) \sim \mathcal{N}(\ln(0.4),0.1)$;
5.	Sc 5a Set knife-edged age at recruitment = 3 years;
6.	Sc 6b Reduce the overall observation error term $\sigma_O = 0.15$; and
7.	Sc 7b Reduce the SD in the likelihood for the fit to average annual mean weight $\sigma_W = 0.15$.

## Reference model results

Results are presented from the two reference case models, to demonstrate model performance and to provide comparison with the 2018 stock assessment.
Advice, presented in the next section, is based on combined model results in each area.

For both areas, the joint posterior distribution for each model was numerically approximated using the Markov Chain Monte Carlo (MCMC) routines built into AD Model Builder (Metropolis-Hastings algorithm) [@fournier2012]. 
Posterior samples were drawn every 5,000 iterations from a chain of length 10 million, resulting in 2,000 posterior samples (the first 1,000 samples were dropped to allow for sufficient burn-in).

Model convergence was informed by visual inspection of trace and autocorrelation plots (not shown), and the statistics $\hat{R}$, the potential scale reduction statistic, which should approach 1.0 as the chains are consistent with convergence, and $n_\mathrm{eff}$, which measures the effective number of MCMC independent samples after accounting for autocorrelation [@gelman1992; @gelman2014; see descriptions in @forrest2020].

### Area 3CD

Reference case model fits to the data were generally typical of all sensitivity cases.
The model diagnostics were consistent with convergence, and posterior sample autocorrelation was relatively minor for most parameters (Table \@ref(tab:tab-param-est-table-3cd)).
Model fits to the catch were near perfect by design (standard deviation in log likelihood was set to 0.05) and are not shown.
Model fits to the four indices of abundance are shown in Figure \@ref(fig:fig-base-index-fits-3cd).
The reference model followed the trends of the two fishery-independent indices (Figure \@ref(fig:fig-base-index-fits-3cd)a and d), but did not closely fit the 2012, 2014 and 2016 data points in WCVI Synoptic survey (Figure \@ref(fig:fig-base-index-fits-3cd)a).
This is likely because of large differences between low points (2012 and 2018) and high points (2014 and 2016) in the survey observations.
Similarly, while the model closely followed the major patterns in the historical CPUE index (Figure \@ref(fig:fig-base-index-fits-3cd)b), it did not capture all the peaks in the modern series (Figure \@ref(fig:fig-base-index-fits-3cd)c).
Fits such as this tend to occur when there is no other information (such as age composition data or contrasting mean weight data) to help resolve large fluctuations in observed indices.

@forrest2015 and @forrest2020 considered goodness of fit to the indices of abundance to be a primary driver of uncertainty in their assessments, as estimates of productivity parameters were sensitive to how well the model fit observed peaks in the indices.
They presented a number of sensitivity analyses to treatment of the observation error parameter $\sigma_O$, one of which is included in the model-averaging set in each area (Sc 6b).

As in the 2018  assessment [@forrest2020], the model tended to underestimate annual mean weight, especially in the early part of the time series (Figure \@ref(fig:fig-base-mean-weight-3cd)).
This is most likely because most of the length measurements in this part of the time series came from fish classified as "keepers", i.e., not released at sea (see @forrest2015 for discussion of this issue for the Area 5AB and 5CD stocks).
Smaller, released fish are therefore likely underrepresented in the annual mean weight data prior to the introduction of at-sea observers in 1996.
A scenario with a smaller value of $\sigma_W$, which controls the fit to the mean weight in the likelihood function, is included in the model-averaging set in each area (Sc 7b).

Reference model parameter estimates are shown in Table \@ref(tab:tab-param-est-table-3cd).
Notably, the median estimated value of natural mortality, $M$, was 0.45 *y*^-1^ (0.41--0.49 *y*^-1^) in the current assessment (Table \@ref(tab:tab-param-est-table-3cd)), compared to 0.42 *y*^-1^ (0.39--0.46 *y*^-1^) in 2018 [@forrest2020].
Values in parentheses here and elsewhere refer to lower and upper bounds of the 95% credible interval. 
The larger 2020 estimates of $M$ suggest that the model is partially explaining the decreased biomass through greater natural mortality, although there was considerable overlap between the current and 2018 credible intervals.

### Area 5ABCD

As for Area 3CD, reference case model fits to the data were typical of all sensitivity cases.
The model diagnostics were consistent with convergence, and posterior sample autocorrelation was relatively minor for most parameters (Table \@ref(tab:tab-param-est-table-5abcd)).

The MPD (mode of the posterior distribution) model fits to the five indices of abundance are shown in Figure \@ref(fig:fig-base-index-fits-5abcd).
The model followed the general trends of the three fishery-independent indices, but could not fit some of the larger peaks (for example 2004 and 2005 peaks in the Queen Charlotte Sound Synoptic Survey, and the 2009 and 2013 peaks in the Hecate Strait Synoptic Survey, Figure \@ref(fig:fig-base-index-fits-5abcd)b and c).
Similarly, the model followed the major patterns in the two CPUE indices but did not capture all the peaks (Figure \@ref(fig:fig-base-index-fits-5abcd)d and e).
As in previous assessments, the model tended to underestimate annual mean weight, especially between 1970 and 2000 (Figure \@ref(fig:fig-base-mean-weight-5abcd)), likely for similar reasons described for Area 3CD.

Reference model parameter estimates are shown in Table \@ref(tab:tab-param-est-table-5abcd).
The range of the posterior estimate of $M$ was was nearly identical in the current assessment, at 0.31 *y*^-1^ (0.28--0.34 *y*^-1^), compared to 0.31 *y*^-1^ (0.28--0.35 *y*^-1^) in the 2018 assessment [@forrest2020].

## Indicators of current stock status 

Management advice for both stocks is based on the results of the combined models described above in the model scenarios section. 
The RPR meeting held in October 2018 reviewed the Reference Case model and the suite of sensitivity runs described above, and concluded that no one model adequately represented the uncertainty associated with these stock assessments.
Consequently, RPR participants agreed to adopt an approach that combined model runs to include a greater range of plausible uncertainties associated with these stocks.

### Area 3CD

Posterior estimates of reference points and stock status from the combined model-averaged set are provided in Table \@ref(tab:tab-ref-points-table-avg-3cd).
At the beginning of the 2021 fishing year, under the assumed 2020 catch level, median biomass is projected to be 14,099 t (6,008--47,920 t).
Median fishing mortality for the 2020 fishing year is projected to be 0.006 *y*^-1^ (0.002--0.015 *y*^-1^).
The median estimated LRP and USR are estimated to be 8,603 t (3,134--28,435 t) and 28,436 t (12,254--84,756 t), respectively.
The median estimated LRR is estimated to be 0.065 *y*^-1^ (0.021--0.187 *y*^-1^). 
Median biomass in 2021 relative to the LRP and USR is estimated to be 1.64 (1.01--3.59) and 0.507 (0.313--0.962), respectively.
Median fishing mortality relative to the LRR is estimated to be 0.083 (0.038--0.137) (Table \@ref(tab:tab-ref-points-table-avg-3cd)).

The average posterior biomass and fishing mortality from the combined model-averaged set are shown in Figures \@ref(fig:fig-model-average-biomass-3cd) and \@ref(fig:fig-model-average-f-3cd).
The estimated biomass range was very broad.
Combined average posterior results from all models indicate that the stock in 2020 was just above the LRP (Figure \@ref(fig:fig-model-average-biomass-3cd)).
This is a notable decrease in estimated stock status (median $B_{2021}/\textrm{LRP}$ = 1.64) compared to the 2018 assessment, where median $B_{2019}/\textrm{LRP}$ was 2.07 (2.48--2.16)) [@dfo2019].
The estimated fishing mortality range was also broad (Figure \@ref(fig:fig-model-average-f-3cd)), reflecting the range of biomass estimates.
However, recent estimates of fishing mortality were well below the median LRR (Figure \@ref(fig:fig-model-average-f-3cd)).  

### Area 5ABCD

Posterior estimates of reference points and stock status from the combined model-averaged set are provided in Table \@ref(tab:tab-ref-points-table-avg-5abcd).
At the beginning of the 2021 fishing year, under the assumed 2020 catch level, median biomass is projected to be 19,634 t (11,318--40,603 t).
Median fishing mortality for the 2020 fishing year is projected to be 0.027 *y*^-1^ (0.013--0.049 *y*^-1^).
The median estimated LRP and USR are estimated to be 9,814 t (5,662--20,881 t) and 33,409 t (21,630--59,004 t), respectively.
The median estimated LRR is estimated to be 0.15 *y*^-1^ (0.09--0.28 *y*^-1^).
Median biomass in 2021 relative to the LRP and USR is estimated to be 1.96 (1.40--3.11) and 0.59 (0.39--0.89), respectively.
Median fishing mortality relative to the LRR is estimated to be 0.17 (0.11--0.27) (Table \@ref(tab:tab-ref-points-table-avg-5abcd)).

The average posterior biomass and fishing mortality from the combined model-averaged set are shown in Figures \@ref(fig:fig-model-average-biomass-5abcd) and \@ref(fig:fig-model-average-f-5abcd).
As for Area 3CD, the estimated biomass range was very broad.
Combined average posterior results from all models indicate that the stock in 2020 was above the LRP, within the Cautious Zone.
The estimated fishing mortality range was also broad (Figure \@ref(fig:fig-model-average-f-5abcd)), reflecting the range of biomass estimates.
Recent estimates of fishing mortality were well below the median LRR.

## 2021 harvest advice

Performance measures were calculated over a sequence of alternative 2021 projected catch levels and are based on posterior samples for a one-year projection to the beginning of 2022.
Uncertainty enters the projections through parameter uncertainty propagated through the modeled time series and recruitment anomalies for the projection year.
The following performance measures were evaluated:

1. $P(B_{2022} < B_{2021})$
1. $P(F_{2021} > F_{2020})$
1. $P(B_{2022} < LRP)$
1. $P(B_{2022} < USR)$
1. $P(F_{2021} > LRR)$

Decision tables were constructed for each area using the equally weighted combined posterior samples [see @forrest2020].

### Area 3CD

For illustration, recent combined average posterior biomass with a one year projection under four alternative catch levels is shown in Figure \@ref(fig:fig-model-average-biomass-3cd-proj).

The model-averaged decision table probabilities are presented in Table \@ref(tab:summary-tab-decision-avg-3cd). In summary:

-	$P(B_{2022} < B_{2021})$ ranged from 55% to 83% over the range of 2021 catch levels.

- $P(F_{2021} > F_{2020})$ ranged from < 1% to > 99%.
The 2020 catch was extrapolated to be approximately 59 t, hence the probability increase between 50 t and 60 t.

- $P(B_{2022} < LRP)$ ranged from < 2% to 10%.

- $P(B_{2022} < USR)$ ranged from 97% to 98%.

- $P(F_{2021} > LRR)$  ranged from < 1% to 98%.

Under a 2021 catch of 500 tonnes (the 2019/20 TAC), there is a 4% probability that biomass in 2021 will be below the LRP (Table \@ref(tab:summary-tab-decision-avg-3cd)).
However, assuming the 2021 catch is of a similar magnitude to the 2020 catch (approximately 59 t), the probability of the 2021 biomass being below the LRP is 2% (Table \@ref(tab:summary-tab-decision-avg-3cd)).
The 2022 biomass is projected to be in the Cautious Zone
(below the USR) with 97--98% probability under all 2021 catch scenarios tested,
including zero catch.

The probability of the fishing mortality exceeding the LRR is less than 1% for all levels of catch up to 400 t.
This probability is based on the maximum LRR (i.e., average estimated fishing mortality rate from 1956--2004).
DFO's precautionary approach policy [@dfo2009] describes the removal reference (i.e., the LRR) as the maximum acceptable removal rate for the stock.
The policy illustrates a harvest control rule with a linear decline in the LRR for stocks in the Cautious Zone.
Such a harvest control rule has not been formally agreed upon for Pacific Cod and, therefore, the probabilities in Table \@ref(tab:summary-tab-decision-avg-3cd) and in previous Pacific Cod advice [@dfo2015; @dfo2019] do not reflect any adjustment to the LRR when the stock is in the Cautious Zone.
If such a harvest control rule were applied, as illustrated in @dfo2009, then probabilities of exceeding the LRR would be higher.
It is recommended that a harvest control rule, which describes any adjustments to the LRR for stocks below the USR, should be agreed upon before the next assessment update.

### Area 5ABCD

Recent combined average biomass with a one year projection under four alternative catch levels is shown in Figure \@ref(fig:fig-model-average-biomass-5abcd-proj).

The model-averaged decision table probabilities are presented in Table \@ref(tab:summary-tab-decision-avg-5abcd).
In summary:

-	$P(B_{2022} < B_{2021})$ ranged from 22% to 91% over the range of 2021 catch levels.

- $P(F_{2021} > F_{2020})$ ranged from < 1% to > 99%.
The 2020 catch was extrapolated to be approximately 425 t, hence the probability increase between 400 t and 500 t.

- $P(B_{2022} < LRP)$ ranged from < 1% to 1%.

- $P(B_{2022} < USR)$ ranged from 98% to 99%.

- $P(F_{2020} > LRR)$  ranged from < 1% to 85%.

Under a 2021 catch of 950 tonnes (the 2018/19 TAC), there is less than 1% probability that biomass in 2021 will be below the LRP (Table \@ref(tab:summary-tab-decision-avg-5abcd)).
Assuming the 2021 catch is of a similar magnitude to the 2020 catch (approximately 425 t), the probability of the 2022 biomass being below the LRP is also
less than 1% (Table \@ref(tab:summary-tab-decision-avg-3cd)).
The 2022 biomass is projected to be in the Cautious Zone
(below the USR) with 98%--99% probability under all 2021 catch scenarios tested, including zero catch.

The probability of the stock exceeding the LRR is less than 1% for all levels of catch up to 1400 t.
As for Area 3CD, if the LRR were adjusted downward because the stock is in the Cautious Zone [@dfo2009], the probabilities of exceeding the LRR would be higher.

## Sources of uncertainty

Uncertainty due to estimated parameters and the weights assigned to various data components was explicitly addressed using a Bayesian approach.
For provision of advice, posterior results from seven alternative model configurations were combined to generate decision tables.
However, this approach only captures uncertainty associated with the set of model configurations included within the assessment and may underestimate greater structural uncertainties.
Additional uncertainties in this assessment stem from:

1. The lack of reliable age composition data for this species, which would provide additional information about recruitment strength and gear selectivity;
1. Relatively short time series of fishery-independent abundance indices, which show no clear trend;
1. Uncertainty in the magnitude of pre-1996 discarding and foreign catches. Underestimation of historical discards could lead to an underestimation of stock productivity;
1. Bias in the length frequency data prior to 1996, due to likely under-representation of lengths of fish that were caught but released at sea;
1. A poor understanding of Pacific Cod stock structure in Pacific waters. For example, connectivity between stocks of Pacific Cod in BC and Alaska is not well understood. Pacific Cod stocks in the Gulf of Alaska have undergone decline since 2017, likely due to warming north Pacific waters [@barbeaux2020], and it is unknown whether there is any relationship between drivers of abundance of these stocks and stocks in BC; and
1. A poor understanding of the relationship between commercial CPUE data and abundance, and how this relationship has been affected over the course of management changes in the fishery.

# Conclusions

This document updates the stock status of Pacific Cod stocks in Area 3CD and 5ABCD at the end of the 2020 fishing year, and provides 2021 catch advice in the form of decision tables.
Currently, both stocks are assessed to be in the Cautious Zone, as was the case in the 2018 assessment [@dfo2019].
However, the Area 3CD stock is estimated to have declined in abundance and is estimated to be closer to the LRP than in the previous assessment.

A critical concern with this assessment is the lack of a WCVI synoptic survey update in 2020.
It is recommended that this area be surveyed as soon as it is feasible, and that this advice be updated when the data are available.
Further analysis of recent survey data including spatial and depth distribution of the stock, and analysis of biological data, such as condition of the fish over time (length-weight relationship) and spatial distribution of length data could also provide insights into possible causes of the apparent rapid decline in abundance.
Other key research recommendations, which would improve understanding of stock and fishery dynamics for both stocks are provided in @forrest2020.
A fully described harvest control rule should be agreed upon before the next assessment update.

\clearpage
