\clearpage

# Tables {#sec:tables}

```{r surv-canadian-table, results='asis'}
dplyr::filter(dat$survey_index, survey_abbrev %in%
  c("SYN HS", "SYN QCS", "SYN WCVI")) %>%
  dplyr::select(survey_abbrev, year, biomass, re, lowerci, upperci, num_sets, num_pos_sets) %>%
  dplyr::mutate(lowerci = round(lowerci/1000, 1), upperci = round(upperci/1000, 1),
    biomass = round(biomass/1000, 1), re = round(re, 2)) %>%
  dplyr::rename(`Survey abbrev.` = survey_abbrev, Year = year, Biomass = biomass,
    CV = re, `Lower CI` = lowerci, `Upper CI` = upperci, Sets = num_sets, `Positive sets` = num_pos_sets) %>%
  dplyr::arrange(`Survey abbrev.`, Year) %>%
  knitr::kable(caption = "Pacific Cod survey data for Canadian trawl surveys in metric tons (without accounting for survey catchability). Positive sets refers to the number of trawl sets that caught Pacific Cod. SYN HS = Hecate Strait synoptic bottom trawl survey; SYN QCS = Queen Charlotte Sound synoptic bottom trawl survey; SYN WCVI = West Coast Vancouver Island synoptic bottom trawl survey .", booktabs = TRUE, linesep = "", 
    format = "pandoc")
```

\clearpage

```{r tab-catch-3cd}
catch.table(catch.3,
            catch.3.discards,
            pre.1996.discards.3cd,
            area = "3CD",
 cap = paste0("Reported catch (mt) of Pacific Cod in Area 3CD ",
              "by Canada and the USA, ",
              min(catch.3$year)+3, "--", max(catch.3$year),
              ". The reported releases at sea (discards) for the period ", min(catch.3$year)+3,
              "--1995 are ",
              "likely unrepresentative of true discarding because the estimates were taken ",
              "from logbooks in the absence of observers. Discard estimates since 1996 are based on at-sea ",
              "observations and are considered to be more representative of true discarding. The 2020 total catch estimate is extrapolated from the combined landings plus discards taken up to September 30, 2020 (see text). Therefore 2020 nominal landings and discards are not shown individually. Numbers are rounded for presentation."), french=french)
```

\clearpage

```{r tab-param-table-3cd, results='asis'}
make.parameters.table(base.model.3cd,
  caption = paste0("Estimated and fixed parameters and prior probability distributions used ",
    "in the Reference Case, Area 3CD. The survey catchability parameter for WCVI ($q_1$) was estimated with the prior probability distribution $\\textrm{Normal}(ln(0.228),0.3)$. The other survey catchability parameters were estimated without priors."),
  omit_pars = c("Log initial recruitment ($\\ln(\\overline{R}_{init})$)",
    "Log mean recruitment ($\\ln(\\overline{R})$)"),
  omit_selectivity_pars = TRUE, french=french)
```

\clearpage

```{r tab-param-est-table-3cd, results='asis'}
pars_est_omit <- c("$\\overline{R}_{init}$", "$\\overline{R}$", "$\\vartheta$","$B_0$")
make.parameters.est.table(base.model.3cd,
  caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
    "97.5\\textsuperscript{th} percentile) and MPD ",
    "estimates of key parameters from the Reference Case, Area 3CD. $R_0$ is in thousands of fish. $\\hat{R}$ is the potential scale reduction statistic and $n_\\mathrm{eff}$ is the effective number of simulation draws (see text). ",
    q.3cd.desc),
  omit_pars = pars_est_omit, french=french)
```

\clearpage

```{r tab-ref-points-table-avg-3cd, results='asis'}
make.ref.points.table(c(base.model.3cd,
                        sens.models.13.sub),
                        lrr_range = 1956:2004,
                        lrp_range = 1986,
                        usr_range = 1956:2004,
                        digits = 2,
                        caption = paste0("Posterior (2.5\\textsuperscript{th} percentile, Median, and ",
                                         "97.5\\textsuperscript{th} percentile) of reference points for ",
                                         "model-averaged Area 3CD. ",
                                         "Biomass is in tonnes. All values are rounded. Ratios were calculated using full posterior distributions and cannot be calculated directly from the table."), french=french)
```
\clearpage
