\clearpage

# Contributors

Contributors to the Science Response.

```{r, echo=FALSE, include=FALSE}
contributors <- tibble::tribble(
  ~Name,          ~Affiliation, ~Role,
  "Robyn Forrest",   "DFO Science, Pacific Region", "Author",
  "Sean Anderson",   "DFO Science, Pacific Region", "Author",
  "Paul Starr", "Canadian Groundfish Research and Conservation Society", "Technical Working Group",
   "Ian Stewart", "International Pacific Halibut Commission", "Reviewer",
   "Daniel Ricard", "DFO Science, Gulf Region", "Reviewer",
   "Dana Haggarty", "DFO Science, Pacific Region", "Steering Committee",
   "Steven Schut", "DFO Science, Pacific Region", "Steering Committee"
)
```

```{r, results='asis'}
csasdown::csas_table(contributors)
```

<!-- Decrease the table index by one to account for the contributors table: -->
<!-- \addtocounter{table}{-1} -->

\MakeApproval

# Sources of Information {-}
<!--
This manually sets the header for this unnumbered chapter.
-->


<!-- The following sets the appropriate indentation for the references -->
\noindent
\vspace{-2em}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\markboth{References}{References}
