\clearpage

# Collaborateurs

```{r, echo=FALSE, include=FALSE}
contributors <- tibble::tribble(
  ~Name,          ~Affiliation, ~Role,
  "Robyn Forrest",   "Direction des sciences, MPO, région du Pacifique", "Auteur",
  "Sean Anderson",   "Direction des sciences, MPO, région du Pacifique", "Auteur",
   "Ian Stewart", "International Pacific Halibut Commission", "Réviseur",
   "Daniel Ricard", "Direction des sciences, MPO, région du Golfe", "Réviseur",
   "Dana Haggarty", "Direction des sciences, MPO, région du Pacifique", "Comité directeur",
   "Steven Schut", "Direction des sciences, MPO, région du Pacifique", "Comité directeur"
)
```

```{r, results='asis'}
csasdown::csas_table(contributors)
```

<!-- Decrease the table index by one to account for the contributors table: -->
<!-- \addtocounter{table}{-1} -->

\MakeApproval

# Sources d'information {-}
<!--
This manually sets the header for this unnumbered chapter.
-->


<!-- The following sets the appropriate indentation for the references -->
\noindent
\vspace{-2em}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}

\markboth{References}{References}
